### ISSUE TITLE
Spark support

### ISSUE THREAD

**Issue by christopheblp** [klarna/HiveRunner#101]
Hi guys,

I wanted to do some queries using spark with a hive table created with hiverunner, is that possible ? I've searched on the forums if anyone has ever tried to do this but it seems not.

This is what I've tried to do : 

This is my class in which I want to process some queries using **spark** : 

```
public class SparkJobsTest {

    private SparkSession spark;

    @Before
    public void setUp() throws Exception {
        spark = SparkSession
                .builder()
                .appName("Java Spark Hive Example")
                .config("spark.master", "local")
                .enableHiveSupport()
                .getOrCreate();
    }

    @Test
    public void queryHiveTable() {
        spark.sqlContext().sql("show databases").show();
    }
}
```

This is the class in which I created a Hive table : 

```
@RunWith(StandaloneHiveRunner.class)
public class MiniClusterHiveTest {

    @Rule
    public TestName name = new TestName();

    @HiveSQL(files = {})
    private HiveShell shell;

    @Before
    public void createDatabaseAndTable() {
        shell.execute("CREATE DATABASE source_db");
        shell.execute("CREATE TABLE source_db.survey (" +
                "a STRING," +
                "b STRING) " +
                "ROW FORMAT DELIMITED " +
                "FIELDS TERMINATED BY ',' " +
                "STORED AS TEXTFILE " +
                "LOCATION '/home/datasets/'");
    }

   // Some tests methods
}
```

When I tried to execute my Spark test class I have this error : 

> java.lang.NoSuchFieldError: HIVE_STATS_JDBC_TIMEOUT
> 
> 	at org.apache.spark.sql.hive.HiveUtils$.formatTimeVarsForHiveClient(HiveUtils.scala:205)
> 	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:286)
> 	at org.apache.spark.sql.hive.HiveExternalCatalog.client$lzycompute(HiveExternalCatalog.scala:66)
> 	at org.apache.spark.sql.hive.HiveExternalCatalog.client(HiveExternalCatalog.scala:65)
> 	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$databaseExists$1.apply$mcZ$sp(HiveExternalCatalog.scala:195)
> 	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$databaseExists$1.apply(HiveExternalCatalog.scala:195)
> 	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$databaseExists$1.apply(HiveExternalCatalog.scala:195)
> 	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:97)
> 	at org.apache.spark.sql.hive.HiveExternalCatalog.databaseExists(HiveExternalCatalog.scala:194)
> 	at org.apache.spark.sql.internal.SharedState.externalCatalog$lzycompute(SharedState.scala:114)
> 	at org.apache.spark.sql.internal.SharedState.externalCatalog(SharedState.scala:102)
> 	at org.apache.spark.sql.hive.HiveSessionStateBuilder.externalCatalog(HiveSessionStateBuilder.scala:39)
> 	at org.apache.spark.sql.hive.HiveSessionStateBuilder.catalog$lzycompute(HiveSessionStateBuilder.scala:54)
> 	at org.apache.spark.sql.hive.HiveSessionStateBuilder.catalog(HiveSessionStateBuilder.scala:52)
> 	at org.apache.spark.sql.hive.HiveSessionStateBuilder$$anon$1.<init>(HiveSessionStateBuilder.scala:69)
> 	at org.apache.spark.sql.hive.HiveSessionStateBuilder.analyzer(HiveSessionStateBuilder.scala:69)
> 	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
> 	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
> 	at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:79)
> 	at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:79)
> 	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
> 	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
> 	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
> 	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:74)
> 	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:638)
> 	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:694)
> 	at MiniClusters.SparkJobsTest.queryHiveTable(SparkJobsTest.java:23)

Is that because it is impossible or because I'm missing something ?

Thanks in advance !

**Comment by massdosage** [comment]
We have had some discussions about using HiveRunner with Spark - see https://groups.google.com/forum/#!topic/hive-runner-user/sSQhhakqW3Q. Although the use case and problems reported with it there look a bit different to this. I'm not aware of anyone doing what you're trying to do but that doesn't mean it's not possible! It's quite possible there needs to be some additional setup to get things working for Spark. What version of Spark are you using? Would it be possible to provide a full unit test (either a dummy project or a fork of HiveRunner with a test added to the tests module) that someone could use to reproduce this?

**Comment by christopheblp** [comment]
Thanks for your reply. 

In order to consult your link, I need some permissions, I just asked for it with my google account. Thanks in advance.
I use Spark version 2.3.0. And this is a link for my test classes : 

https://github.com/christopheblp/MiniClusterTestBigData

 In order to get the same error, you just have to add this dependency to the project : 

```
<dependency>
     <groupId>org.apache.spark</groupId>
     <artifactId>spark-hive_2.11</artifactId>
     <version>2.3.0</version>
     <scope>provided</scope>
</dependency>
```

**Comment by massdosage** [comment]
So I see that this test

https://github.com/christopheblp/MiniClusterTestBigData/blob/master/src/test/java/MiniClusters/MiniClusterHiveTest.java

uses HiveRunner but not Spark. This test:

https://github.com/christopheblp/MiniClusterTestBigData/blob/master/src/test/java/MiniClusters/SparkJobsTest.java

uses Spark's Hive context but not HiveRunner. So I'm a bit confused as to what you are trying to do and where, could you provide some more info about these tests please?

**Comment by massdosage** [comment]
Closing due to lack of activity.
