### ISSUE TITLE
NPE from MetaStore getFilteredObjects

### ISSUE THREAD

**Issue by mattburgess** [klarna/HiveRunner#123]
**Describe the bug**
When running any test, the test passes but there's a whole lot of log spam on the console from the underlying Hive libraries. The start of the stack trace is here:

```java.lang.NullPointerException
	at org.apache.hadoop.hive.ql.security.authorization.plugin.AuthorizationMetaStoreFilterHook.getFilteredObjects(AuthorizationMetaStoreFilterHook.java:77) ~[hive-exec-2.3.7.jar:2.3.7]
	at org.apache.hadoop.hive.ql.security.authorization.plugin.AuthorizationMetaStoreFilterHook.filterDatabases(AuthorizationMetaStoreFilterHook.java:54) ~[hive-exec-2.3.7.jar:2.3.7]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getDatabases(HiveMetaStoreClient.java:1147) ~[hive-metastore-2.3.7.jar:2.3.7]
	at org.apache.hive.hcatalog.common.HiveClientCache$CacheableHiveMetaStoreClient.isOpen(HiveClientCache.java:471) ~[hive-hcatalog-core-2.3.7.jar:2.3.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169) ~[hive-metastore-2.3.7.jar:2.3.7]
	at com.sun.proxy.$Proxy26.isOpen(Unknown Source) ~[?:?]
```

**To Reproduce**

- Clone https://github.com/dwp/dataworks-pdm
- Run `mvn test`

**Expected behavior**
The tests should run as they do now, but without any stack traces on the console.

**Logs**
Please add the log output from HiveRunner when the error occurs, full stack traces are especially useful.

**Versions (please complete the following information):**
 - HiveRunner Version: 5.2.1
 - Hive Versions: 2.3.7

**Additional context**
Initially, I was running this within a docker container, but thinking that might have been a cause of the issue have now run the tests on a standard Linux workstation but the behaviour is the same. https://stackoverflow.com/questions/54369672/puthivestreaming-processor-in-nifi-throws-npe suggests it may have something to do with IP address/hostname resolution but I don't have problems with anything else running on the workstation.

**Comment by massdosage** [comment]
I'm afraid I can't reproduce this, I followed the steps above (I had to change the path location of the data in `contract.sql`) but other than that I made no modifications and I see this in the terminal when the tests are run:

> [INFO] -------------------------------------------------------
> [INFO]  T E S T S
> [INFO] -------------------------------------------------------
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/awoodhead/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/home/awoodhead/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.6.2/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
> [INFO] Running uk.gov.dwp.dataworks.pdm.ContractTest
> log4j:WARN No appenders could be found for logger (org.apache.hadoop.hive.conf.HiveConf).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
> OK
> OK
> OK
> OK
> OK
> OK
> OK
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.367 s - in uk.gov.dwp.dataworks.pdm.ContractTest
> 

So I think this is some kind of interaction with the setup on your machine, perhaps in the networking like you suggested. Unless someone else can reproduce this and suggest changes to fix it I'm not sure what else we can do.

**Comment by mattburgess** [comment]
Thanks @massdosage . I guess it depends on when you cloned that repo :) We found the really odd fix/workaround and merged it at https://github.com/dwp/dataworks-pdm/commit/2d60a5fa43009f1cede5a712c08aa6f03968a632.

Basically, when we explicitly added a dependency of `hive-serde` to `pom.xml`, those NPEs went away and we were left with nice clean console output. I'm a bit confused as to how that "fix" actually helps things though.

Whilst I don't want to waste too much of your time on this issue it would be nice to know that you can replicate it by perhaps checking out at commit `56c7bfc5b15bf781c96477b24d38effbe7cebe16` and re-running the test.

**Comment by massdosage** [comment]
I checked out the code at the commit you suggested and I see the NPE's but then the test also fails with

```
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot validate serde: 
org.openx.data.jsonserde.JsonSerDe
        at uk.gov.dwp.dataworks.pdm.ContractTest.testContractTable(ContractTest.java:54)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Cannot validate serde: org.openx.data.jsonserde.JsonSerDe
        at uk.gov.dwp.dataworks.pdm.ContractTest.testContractTable(ContractTest.java:54)
Caused by: java.lang.ClassNotFoundException: Class org.openx.data.jsonserde.JsonSerDe not found
        at uk.gov.dwp.dataworks.pdm.ContractTest.testContractTable(ContractTest.java:54)
```

which I assume is why you added `hive-serde` as a dependency and this then made the NPE go away. Based on my experience with the Hive libraries and the tangled web of dependencies they bring with them and the unexpected ways these then interact I think we could end up spending a lot of time trying to figure out the root cause with little benefit. My guess is that the serde dependency pulls in some other transitive dependency which in turn activates a slightly different code path and this in turn doesn't hit the NPE. If the tests are passing and your output looks good now I'd recommend keeping this can of worms closed ;)

**Comment by mattburgess** [comment]
I thought you may say that 😂. Hopefully just having this issue in Google results will help the next person that hits this.
