### ISSUE TITLE
ERROR hiverunner.StandaloneHiveRunner Failed to set permissions of path: C:\ to 0700

### ISSUE THREAD

**Issue by thaparraj** [klarna/HiveRunner#2]
When running unit test, encountered following error message:
ocalscratchdir\hive_2014-07-02_16-00-01_009_6895163325323467224-1 to 0700
java.lang.IllegalStateException: Failed to ping HiveServer: Query returned non-zero code: 40000, cause: FAILED: RuntimeException java.io.IOException: Failed to set permissions of path: C:\cygwin64\tmp\junit7581111814416842686\localscratchdir\hive_2014-07-02_16-00-01_009_6895163325323467224-1 to 0700
	at com.klarna.hiverunner.HiveServerContainer.pingHiveServer(HiveServerContainer.java:149)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:74)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:92)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:138)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:95)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:49)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:75)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: HiveServerException(message:Query returned non-zero code: 40000, cause: FAILED: RuntimeException java.io.IOException: Failed to set permissions of path: C:\cygwin64\tmp\junit7581111814416842686\localscratchdir\hive_2014-07-02_16-00-01_009_6895163325323467224-1 to 0700, errorCode:40000, SQLState:42000)
	at org.apache.hadoop.hive.service.HiveServer$HiveServerHandler.execute(HiveServer.java:219)
	at com.klarna.hiverunner.HiveServerContainer.pingHiveServer(HiveServerContainer.java:147)

**Comment by PelleUllberg** [comment]
Hi, 

Sorry for the late reply. 

First: Sorry to say that HiveRunner do not run under windows. We have been able to run it with cygwin though.

Could you try to run with the latest release of HiveRunner. I have a vague memory of fixing some file permission a while ago.

best regards
/Pelle

**Comment by xfreece** [comment]
Hi, did you manage to run hiverunner? We're interested in how to run HiveRunner on windows but have not spent time on it so far.

regards
/Stefan

**Comment by massdosage** [comment]
@xfreece - I think @PelleUllberg was suggesting that most people don't use it on Windows but if someone who has a Windows environment wants to try it out and then let us know if the above issue is fixed or not we could take a look. Can you give it a go and report back?

**Comment by PelleUllberg** [comment]
Closing due to inactivity

**Comment by 4ajeet** [comment]
No it does not work on windows, i tries version 3.0.0. And it is due to limitations of File.setWritable() method.
Hadoop also faced same problem so they implemented setWritable() - FileUtils.setWritable(), that works on windows.
Can we do similar for HiveRunner ?
