### ISSUE TITLE
Issue reading from Avro files when using insertInto feature

### ISSUE THREAD

**Issue by prasanis** [klarna/HiveRunner#67]
We are running into an issue when reading from an avro backed table. Here are the sequence of events:
1) Create avro backed table
2) Insert data into it using the InsertInto feature
3) Read from avro table -> Raises a schema mismatch error.

Here is the how the code looks like:

		shell.insertInto(schemaName, tableName)
        	 .withAllColumns()
        	 .addRowsFromDelimited(f, "\t", "NULL")
        	 .commit();

What is interesting is, if I write to the table with shell.execute("Insert into table Values(...)"), the error does not pop up. So it looks like a bug on the addRowsFromDelimited feature.

This does not happen with other table formats (eg: orc), only avro.

Here is the stack trace:

HiveException: java.io.IOException: org.apache.avro.AvroTypeException: Found dummy_avro_table, expecting dummy_avro_table
    at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:171)
    at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:137)
    at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
    at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
    at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
    at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
    at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by massdosage** [comment]
Closing since no feedback received on above comment.
