### ISSUE TITLE
Access files from Hive UDF

### ISSUE THREAD

**Issue by SergeySmith** [klarna/HiveRunner#71]
Hello! I'm trying to test a GenericUDF similar to Hive's in_file() function. My custom function works well in hive shell (via hive and beeline with both local and yarn modes) but when running the same queries in tests I've got the following error:
```
WARN    [IntersectFileUDFTest#testSimpleStringArray]    org.apache.hadoop.security.UserGroupInformation    - PriviledgedActionException as:sergey (auth:SIMPLE) cause:java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.isSymlink(Ljava/io/File;)Z
java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.isSymlink(Ljava/io/File;)Z
	at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:143)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.<init>(LocalJobRunner.java:171)
	at org.apache.hadoop.mapred.LocalJobRunner.submitJob(LocalJobRunner.java:758)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:244)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1307)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1304)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
...
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.isSymlink(Ljava/io/File;)Z
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:139)
	... 50 more
Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.isSymlink(Ljava/io/File;)Z
	at org.apache.hadoop.yarn.util.FSDownload.changePermissions(FSDownload.java:394)
	at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:363)
	at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Job Submission failed with exception 'java.io.IOException(java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.isSymlink(Ljava/io/File;)Z)'
ERROR   [IntersectFileUDFTest#testSimpleStringArray]    org.apache.hadoop.hive.ql.exec.Task    - Job Submission failed with exception 'java.io.IOException(java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.isSymlink(Ljava/io/File;)Z)'
```
I'm using HiveRunner 3.2.0, Hive 1.1.0-cdh5.9.1 for compiling and 1.2.1 in test scope and it works fine for other custom UDFs.

**Comment by oleksandr-yatsuk** [comment]
Sergey, how did you add JAR with your UDF? What path you specified?

**Comment by SergeySmith** [comment]
@oleksandr-yatsuk , actually I'm not adding any jars directly in the tests, my UDFs' classes are in the same project with tests, I just define Hive function via `create temporary function <function_name> as '<package.class>'` and it works for other UDFs just fine. I'm also adding the file to distributed cache via `add file /<path_to_project>/src/test/resources/files/intersect.tsv`. Does HiveRunner currently support distributed cache?

**Comment by SergeySmith** [comment]
To make it simple, forget about my custom function. Say I want to test Hive's `in_file` function. My file:
```
src/test/resources/files/intersect.tsv:

one
two
three
``` 
and the test:
```
@Test
public void testInFile() {
    List<Object[]> expected = shell.executeStatement("select true as res "
            + "union all "
            + "select false as res"
    );

    // might  be redundant
    shell.execute( "add file /<path_to_project>/src/test/resources/files/intersect.tsv;");
    printResult(shell.executeStatement("list files"));

    List<Object[]> result = shell.executeStatement("with t as ( "
            + "select 'one' as word "
            + "union all "
            + "select 'five' as word ) "
            + "select in_file(word, '/<path_to_project>/src/test/resources/files/intersect.tsv') from t"
    );

    assert(expected.size() == 2);
    assertEquals(2, result.size());
    assertArrayEquals(expected.get(0), result.get(0));
    assertArrayEquals(expected.get(1), result.get(1));
}

public void printResult(List<Object[]> result) {
    System.out.println(String.format("Result from %s:",name.getMethodName()));
    for (Object[] row : result) {
        System.out.println(Arrays.asList(row));
    }
}
```
got the same error, the file is added to the distributed cache though.

**Comment by massdosage** [comment]
Could you please try HiveRunner 3.2.1 (which was released today) and let us know if this is still an issue? Also, it's probably best to use the same version for all Hive libraries that you are using otherwise you're likely to get version mismatches in the libraries that they in turn depend on.

**Comment by massdosage** [comment]
What versions of Hadoop and Hive are you using? My guess is that there is a version conflict with a version of Apache commons FileUtils. Can you see what version of it is being resolved too?

**Comment by SergeySmith** [comment]
Ok, i've managed to solve the problem.
I was using Hive version 1.2.1. I've tried Hadoop versions 2.5.2, 2.6.0 and 2.7.6 but the issue didn't disappear. With Hadoop version 2.7.x I've got class not found exception and when I've added commons-io to my pom.xml:
```xml
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.6</version>
</dependency>
```
the issue disappear. 
Thanks!
