### ISSUE TITLE
HiveRunner confuse by multiple HiveConf on the classpath

### ISSUE THREAD

**Issue by labbedaine** [klarna/HiveRunner#80]
I would like to unit test my Hive scripts in the project where I run the production java code.  HiveRunner works well when isolated but doesn't play very nicely when hive-jdbc is on the classpath.  If I understand the Hive source code, it looks for a class HiveConf and use it for instanciation.  Right now I have 2 HiveConf on the classpath, one from **hive-exec** and another one from **hive-common**.  If I remove the hive-jdbc depedency from my project the unit test pass.

The error is the following.  Could you please help.

`java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive configuration: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:102)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error applying authorization policy on hive configuration: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:114)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:100)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:127)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:112)
	... 11 more
Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1550)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1548)
	... 19 more
Caused by: java.lang.NoSuchFieldError: METASTORE_BATCH_RETRIEVE_OBJECTS_MAX
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:207)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
	... 24 more`

**Comment by patduin** [comment]
That sounds like a version mismatch.
What version are your hive dependencies and what version is HiveRunner using?
Either version doesn't seem to have the field "METASTORE_BATCH_RETRIEVE_OBJECTS_MAX"

Try to sync the versions, use the same version as hiveRunner is using or override HiveRunner dependencies with the version you want in your project.

Hope this helps.

**Comment by labbedaine** [comment]
HiveRunner 3.2.0

hive-exec 1.2.1 transitive dependencies from hiverunner
hive-common 2.0.1 transitive dependencies from hive-jdbc (2.0.1)

hive-common 1.2.1 was omitted for conflict

**Comment by patduin** [comment]
ok you could try to lower hive-jdbc to 1.2.1 if that's an option.

Or override hive-exec to 2.0.1, HiveRunner-3.2.0 might have problems with that (there is a branch of HiveRunner using hive 2.3.0 that might be of help in this scenario branch is here https://github.com/klarna/HiveRunner/tree/Hive-2.3.0).

**Comment by labbedaine** [comment]
My production code is set to use hive-jdbc-2.0.1, so I think I would like to use the same version with HiveRunner.


<dependency>
<groupId>com.klarna</groupId>
<artifactId>hiverunner</artifactId>
<version>3.2.0</version>
<scope>test</scope>
<exclusions>
<exclusion>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-log4j12</artifactId>
</exclusion>
<exclusion>
	<groupId>org.datanucleus</groupId>
	<artifactId>datanucleus-api-jdo</artifactId>
</exclusion>
<exclusion>
	<groupId>org.datanucleus</groupId>
	<artifactId>datanucleus-core</artifactId>
</exclusion>
<exclusion>
	<groupId>org.datanucleus</groupId>
	<artifactId>datanucleus-rdbms</artifactId>
</exclusion>
</exclusions>
</dependency>
<dependency>
<groupId>org.apache.hive</groupId>
<artifactId>hive-jdbc</artifactId>
<version>2.0.1</version>
<exclusions>
<exclusion>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-log4j12</artifactId>
</exclusion>
</exclusions>
</dependency>
<dependency>
<groupId>org.apache.hive</groupId>
<artifactId>hive-exec</artifactId>
<version>2.0.1</version>
</dependency>



`java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive configuration: Hive metastore database is not initialized. Please use schematool (e.g. ./schematool -initSchema -dbType ...) to create the schema. If needed, don't forget to include the option to auto-create the underlying database in your JDBC connection string (e.g. ?createDatabaseIfNotExist=true for mysql)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:102)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error applying authorization policy on hive configuration: Hive metastore database is not initialized. Please use schematool (e.g. ./schematool -initSchema -dbType ...) to create the schema. If needed, don't forget to include the option to auto-create the underlying database in your JDBC connection string (e.g. ?createDatabaseIfNotExist=true for mysql)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:114)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:100)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	... 8 more
Caused by: java.lang.RuntimeException: Hive metastore database is not initialized. Please use schematool (e.g. ./schematool -initSchema -dbType ...) to create the schema. If needed, don't forget to include the option to auto-create the underlying database in your JDBC connection string (e.g. ?createDatabaseIfNotExist=true for mysql)`

**Comment by PelleUllberg** [comment]
Hi,

HiveRunner does not use jdbc so it does not matter what version you run for
your hiverunner tests. I understand you might have other tests as well, and
for those it off course makes sense to use the production version of the
jdbc client. Usually when I hit these kind of problems I modularise my
project so that my HiveRunner tests runs with a classpath that misses the
offending libraries.

regards
/Pelle

**Comment by massdosage** [comment]
I would recommend doing whatever is necessary to ensure *all* Hive dependencies are the same version, above looks like there was a mix of Hive versions 1.2.1 and 2.0.1. If all the Hive libraries don't match then all bets are off. Feel free to re-open if this issue still exists once the above has been done.
