### ISSUE TITLE
Parquet Support

### ISSUE THREAD

**Issue by lbollar** [klarna/HiveRunner#82]
This might be an issue with the Hive version being 0.14, but is "STORED AS PARQUET" allowed as an option when creating tables?

If I use parquet format, I get the following,

```
java.lang.RuntimeException: Should never be used
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getRecordWriter(MapredParquetOutputFormat.java:76)
	at org.apache.hive.hcatalog.mapreduce.FileOutputFormatContainer.getRecordWriter(FileOutputFormatContainer.java:102)
	at org.apache.hive.hcatalog.mapreduce.HCatOutputFormat.getRecordWriter(HCatOutputFormat.java:260)
	at org.apache.hive.hcatalog.data.transfer.impl.HCatOutputFormatWriter.write(HCatOutputFormatWriter.java:95)
	at com.klarna.hiverunner.data.TableDataInserter.insert(TableDataInserter.java:48)
	at com.klarna.hiverunner.data.TableDataInserter.insert(TableDataInserter.java:33)
	at com.klarna.hiverunner.data.InsertIntoTable.commit(InsertIntoTable.java:188)
	at com.apple.hivetests.HiveTest.setupTargetDatabase(HiveTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:177)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:748)
```

removing this and using ORC format works fine.

**Comment by massdosage** [comment]
Could you please upgrade to the latest version of HiveRunner(3.2.1) which in turn was built using Hive 1.2.1 and let us know whether this is still an issue?

**Comment by massdosage** [comment]
Closing since no feedback received to above request to try on a new version.
